### ISSUE TITLE
Webpack 2 - ERROR in fetch.editor.js from UglifyJs Invalid assignment

### ISSUE THREAD

**Issue by pionl** [sindresorhus/debounce-fn#1]
Hi, 
thank you for the FCE, works as required (finally don't need to create my seTimeout combination).

When I'm using importing the package while developing, no problem occurs. But when I want to compress the code with UglifyJS, error is raised.

```
ERROR in view.js from UglifyJs
Invalid assignment [./~/debounce-fn/index.js:4,0][view.js:9402,31]
```

Using web pack 2 with babel.

```javascript
import debounceFn from 'debounce-fn'
```

Thank you for your help.
Martin

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
