### ISSUE TITLE
type:module doesn't play nice with esm package

### ISSUE THREAD

**Issue by dkebler** [sindresorhus/debounce-fn#14]
the esm package is great for allowing import of cjs packages but hates when `type:module` is in package.json

See my comments under the pr
https://github.com/sindresorhus/debounce-fn/pull/13#issuecomment-815054467

How to load "old" cjs packages (too many will never be updated) along with new esm ones at the same time seamlessly??

I'm not interested in going back to babel to solve this.

See here for ideas of dual support
https://2ality.com/2019/10/hybrid-npm-packages.html
https://2ality.com/2019/10/hybrid-npm-packages.html#variant%3A-avoiding-.mjs

Will you support both until such a time as cjs dies an deserved death?

**Comment by dkebler** [comment]
maybe this is the way to go?  Still kinda ugly then all old cjs dependencies are updated and all my esm code and any already esm packages are good to go without using that std/esm package/flag

https://www.npmjs.com/package/esinstall

**Comment by sindresorhus** [comment]
I think the most pragmatic solution is clear, change your imports. Anything else is a losing battle on your part as a large part of the community will move to native ESM this year.

For example, when `make-dir` moves to ESM, you will not be able to keep your imports `import { sync as mkdir } from 'make-dir'` anyway as I would change it to `import {makeDirectoryAsync} from 'make-dir'`.

I have no plans to do dual-exports.
