### ISSUE TITLE
Package tags are misleading

### ISSUE THREAD

**Issue by ixth** [sindresorhus/debounce-fn#2]
Is it really related to throttle? It seems like I can't use it to throttle calls.

**Comment by SamVerschueren** [comment]
Can you give an example at what you tried?

**Comment by ixth** [comment]
Well, it's not really a thing I tried, but I need a throttling behaviour: I want to make repeated calls every _n_ milliseconds when events are emitted more frequently. Like here:
![](http://benalman.com/images/projects/jquery-throttle-debounce/throttle-no_trailing.png)

As I understand, debounce provides another behaviour.

**Comment by fregante** [comment]
Debounce and throttle are often confused one for the other. It makes sense that this appears for the throttle search, while still clearly having `debounce` in the name.
