### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by 6ewis** [sindresorhus/debounce-fn#4]
It will fail to minify in some instances because of es6. It's safer to use es5. (example: people using the old version of CRA from React will run into issue)

**Comment by 6ewis** [comment]
https://github.com/sindresorhus/debounce-fn/pull/3

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by 6ewis** [comment]
@sindresorhus it's not always straight forward to simply 'upgrade'. CRA to CRA2 is not as straight forward as it sounds. I think it's easier to write the lib in es5 and it's actually the recommended approach for libs, but your call.

**Comment by ljharb** [comment]
It's also highly dangerous to transpile dependencies, CRA v2's decision notwithstanding. Transpilation comes with caveats that nobody but the author can know are safe to accept or not.
